### ISSUE TITLE
Archive sunspot darkening and facular brightening inputs

### ISSUE THREAD

**Issue by ocoddington** [dlindhol/nrlssi#33]
Due to the variability in Univ. of Bremen Mg II index (see git issue), and potentially the USAF SOON network sunspot records, we will need to formally archive the files used as input to particular versions (really, creation dates) of the NRL 2 models outputs.  
I believe the metadata in the .nc output should reference the names of these input files as well to provide transparency and traceability. What is the best approach to formalize this need?

**Comment by dlindhol** [comment]
For the v02r00 release, I have made "final" copies of the input data and put them in /lisird/public/lasp/nrl2/ with a README. LaTiS datasets are configured for each. The IDL code will get input from here when run with the "final" keyword.

**Comment by dlindhol** [comment]
LaTiS URLs to the final inputs:
http://lisird-dev:8090/lisird3/latis/nrl2_sunspot_darkening_v02r00
http://lisird-dev:8090/lisird3/latis/nrl2_facular_brightening_v02r00
These are currently internal to LASP, but will be changed once lisird3 is released/deployed.

**Comment by dlindhol** [comment]
Other related inputs: http://lisird-dev:8090/lisird3/latis/...
usaf_sunspot_regions_v02r00: snapshot of our cleaned up copy of the NGDC data, used for the final darkening for 1983-2014.
lasp_sunspot_darkening_v02r00.tsml: From our process_sunspot_blocking code. 1983-2014 used for final input.
lean_spot_fac: darkening and brightening data from Judith for 1882-2014. We use these fac values but the spot values only up through 1982.

Dataset names without the version will serve the preliminary data.

**Comment by dlindhol** [comment]
Migrated to NRLSSI-48
