### ISSUE TITLE
Preliminary and Final Flag - designated by date?

### ISSUE THREAD

**Issue by ocoddington** [dlindhol/nrlssi#35]
The flag will be used for our operational processing, and to indicate to user in LaTiS what 

Need to force data downloads to utilize "final" input data for those time periods, and then transition to "preliminary" data inputs for time periods where a final record has not been archived.
Doug has idea to use date of latest data in the final product to define the transition point.  

This will require additional logic in get_sunspot_blocking and get_mg_index.

**Comment by dlindhol** [comment]
I put the final input data files in /lisird/public/lasp/nrl2/ for LaTiS to serve.
I'm adding "final", "prelim", and "dev" keywords to the IDL code:
final: will use the data that has been released to NCDC (v02r00)
prelim: will use the final data with newer data appended
dev: will get sunspot darkening by invoking the IDL process, and potentially provide a hook to use different MgII index datasets

**Comment by dlindhol** [comment]
Migrated to NRLSSI-46
