### ISSUE TITLE
need CF-compliant time variable for .nc files

### ISSUE THREAD

**Issue by ocoddington** [dlindhol/nrlssi#39]
Time units, such as "days", with a reference time (since ref time) are required for the time variable for CF compliance. 
See CF: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#time-coordinate

Can we use Modified Julian Date? The data structure passed to the write routines already contains this variable.

**Comment by dlindhol** [comment]
Fixed for the daily writers. I will take care of the others when I implement the cell_methods.
We'll also include the iso_time to give people a human readable option.
