### ISSUE TITLE
Restrict sunspot area observing stations to ten

### ISSUE THREAD

**Issue by ocoddington** [dlindhol/nrlssi#42]
; 1=LEAR
; 2=CULG
; 3=SVTO
; 4=RAMY
; 5=BOUL
; 6=MWIL
; 7=HOLL
; 8=PALE
; 9=MANI
;      10=ATHN

**Comment by dlindhol** [comment]
Added this list as the default in process_sunspot_blocking. It can still be overriden by calling it with a 'stations' argument.

**Comment by dlindhol** [comment]
I also convert the station name from the data to upper case when looking for matches, just in case.
