### ISSUE TITLE
Addtl global attributes for replacing "preliminary files" with "final files"

### ISSUE THREAD

**Issue by ocoddington** [dlindhol/nrlssi#44]
Additional global attribute metadata will be required, when we produce preliminary files, and then subsequently replace these with final files.

Per Submission Agreement, we will need to provide the following:  
The Provider will also label the “final” data that replaces "preliminary" data as follows:
Remove “preliminary” from the version field in the file name, i.e., “v02r00”
Remove “preliminary” from the netCDF global attribute product_version
Indicate that this “final” data file replaced the previous “preliminary” data file in the history global attribute
Update the date_created and date_modified global attributes

**Comment by ocoddington** [comment]
Revisions to the writer routines accomplish some of the above.  Remaining challenges would be: 
1. Indicate that this “final” data file replaced the previous “preliminary” data file in the history global attribute (need to add this attribute)
2. Update date_modified global attributes (need to add this attribute).

**Comment by dlindhol** [comment]
migrated to NRLSSI-45
